### ISSUE TITLE
Telegram conversation node with empty fields

### ISSUE THREAD

**Issue by brunoamaral** [guidone/node-red-contrib-chatbot#438]
I use a few workflows with a redbot telegram bot, and they appear to be working without any maintenance.

Today I was creating a new one, and found out that I can't choose any configuration settings, the dropdown fields are empty even though the other flows are working. Their dropdown fields also show up as empty;

![Captura de ecrã 2020-09-03, às 00 51 53](https://user-images.githubusercontent.com/543344/92048783-8ae3c080-ed80-11ea-833b-b719db500871.png)
Any idea on what I can do to track down what is going on?

**Comment by remygiraud** [comment]
If you choose the transport first, same thing?
Otherwise, what is your version of redbot?
There was a bug in 0.17.1 (look at https://github.com/guidone/node-red-contrib-chatbot/issues/347) it was fixed in 0.18.2.

**Comment by brunoamaral** [comment]
Yes, the transport is also empty. 

![image](https://user-images.githubusercontent.com/543344/93122673-d53d3980-f6be-11ea-8fcf-672db42aded8.png)

There was also a pending update for version 0.19.7, but it still doesn't show any options.

**Comment by brunoamaral** [comment]
I have been trying to debug this and noticed that there is a JS file returning 404, `/redbot/globals`.

Since this server is using domain.tld/nodered/, I figured that could be the issue, but the /nodered/redbot/globals is also not found. 

I'm stumped right now, what else could I do to track down the issue?

**Comment by brunoamaral** [comment]
If anyone is having the same issue, accessing your node-red from server.lan:1880/directory will work around it.

**Comment by brunoamaral** [comment]
This seems to be fixed in the recent version of Node-Red.
